### PR TITLE
Merge upstream 1.1.4

### PR DESCRIPTION
**Pull request by kluo**
@stvstnfrd

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@kluo This seems reasonable; where there any conflicts?

**Comment by stvstnfrd** [comment]
BTW: I added this PR to the checklist.

**Comment by kluo** [comment]
@stvstnfrd No conflicts, cool if I merge?

**Comment by stvstnfrd** [comment]
@kluo How do we reference/deploy this? Do we pin to a specific SHA?
Is there any risk of merging this to master before we're using it in production?

**Comment by dcadams** [comment]
Is this part of the ORA2 merge and if so, why would we merge it before that is ready?

**Comment by kluo** [comment]
Don't need to merge since we are no longer using our custom score override code in favor of edx.org's

**Pull request closed without merging**
